GESTURE_PHRASES = {
    "A": "Hello",
    "B": "Good Morning",
    "C": "Good Evening",
    "D": "Good Night",
    "E": "Thank You",
    "F": "Sorry",
    "G": "Please",
    "H": "Yes",
    "I": "No",
    "J": "Help",
    "K": "Water",
    "L": "Food",
    "M": "Stop",
    "N": "Wait",
    "O": "Come Here",
    "P": "Go",
    "Q": "What is your name?",
    "R": "Where are you?",
    "S": "I am fine",
    "T": "How are you?",
    "U": "Nice to meet you",
    "V": "Call me",
    "W": "Bathroom",
    "X": "Pain",
    "Y": "I Love You",
    "Z": "Okay"
}
